import { createServer } from 'node:http'
import { once } from 'node:events'
import { test, expect } from '@playwright/test'
test('embedded UI registration, login, settings and task navigation', async ({page,request}, testInfo) => {
 const server=createServer((req,res)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({code:200,data:{content:[{name:'Mayday.2026.1080p.mkv',is_dir:false,size:10,sign:'test'},{name:'Mayday.2026.2160p.DV.mkv',is_dir:false,size:20,sign:'test'}],total:2}}))})
 server.listen(0,'127.0.0.1');await once(server,'listening')
 const port=(server.address() as {port:number}).port
 const errors:string[]=[]
 page.on('dialog',d=>d.accept())
 page.on('pageerror', e=>errors.push(e.message))
 const registered=await request.post('/api/auth/sign-up',{data:{username:'browser',password:'browser-secret'}})
 expect((await registered.json()).code).toBe(200)
 await page.goto('/auth/login')
 await page.locator('input[name=username]').fill('browser')
 await page.locator('input[name=password]').fill('browser-secret')
 await page.locator('button[type=submit]').first().click()
 await expect(page).not.toHaveURL(/auth\/login/)
 await page.goto('/settings')
 await expect(page.locator('#tmdbLanguage')).toBeVisible()
 const login=await request.post('/api/auth/sign-in',{data:{username:'browser',password:'browser-secret'}})
 const token=(await login.json()).data.token
 const config=await request.post('/api/openlist-config',{headers:{Authorization:`Bearer ${token}`},data:{username:'example',baseUrl:`http://127.0.0.1:${port}`,token:'example'}})
 const id=(await config.json()).data.id
 const task=await request.post('/api/task-config',{headers:{Authorization:`Bearer ${token}`},data:{taskName:'browser task',openlistConfigId:id,path:'/media',libraryType:'movie',isActive:true}})
 expect((await task.json()).code).toBe(200)
 await page.goto(`/task-management/${id}`)
 await expect(page.getByText('example',{exact:false}).first()).toBeVisible()
 await page.reload()
 await expect(page).not.toHaveURL(/auth\/login/)
 await page.getByText('画质筛选预览',{exact:true}).click()
 await expect(page.getByText('共 2 个视频，保留 1 个，过滤 1 个。',{exact:true})).toBeVisible()
 await expect(page.getByText('保留：/media/Mayday.2026.2160p.DV.mkv',{exact:true})).toBeVisible()
 await expect(page.getByText('过滤：/media/Mayday.2026.1080p.mkv',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'关闭',exact:true}).click()
 await page.getByTitle('立即执行' ,{exact:true}).click()
 await page.getByText('全量执行',{exact:true}).click()
 await expect(page.getByText('本次任务已完成',{exact:true})).toBeVisible({timeout:15000})
 // Exercise long-running, indeterminate and failed progress without waiting for remote services.
 let progressRun: Record<string, any> = {id:901,status:'RUNNING',stage:'DISCOVERY',progress:0,startedAtUnixMs:Date.now()-65000,currentFile:'/media/电影收藏',isIncremental:true}
 await page.route('**/api/task-config/*/runs/latest', route => route.fulfill({json:{code:200,data:progressRun}}))
 await page.reload()
 const card=page.getByTestId('task-progress')
 await expect(card.getByText('扫描文件',{exact:true})).toBeVisible()
 await expect(card.getByRole('progressbar')).not.toHaveAttribute('aria-valuenow')
 progressRun={...progressRun,stage:'METADATA',progress:37,total:120,processed:42,skipped:6,failed:1,currentFileIndex:50,currentFile:'/media/电影收藏/星际穿越 (2014)/Interstellar.2014.2160p.BluRay.REMUX.mkv'}
 await expect(card.getByText('刮削元数据',{exact:true})).toBeVisible()
 await expect(card.getByRole('progressbar')).toHaveAttribute('aria-valuenow','37')
 await page.screenshot({path:testInfo.outputPath('progress-desktop.png'),fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await card.scrollIntoViewIfNeeded()
 await page.screenshot({path:testInfo.outputPath('progress-mobile.png'),fullPage:true})
 expect(await card.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
 await page.route('**/api/task-config/*/cancel', route=>route.fulfill({json:{code:400,message:'取消暂不可用'}}))
 await card.getByRole('button',{name:'取消任务',exact:true}).click()
 await expect(card.getByRole('alert')).toHaveText('取消暂不可用')
 await expect(card.getByRole('button',{name:'取消任务',exact:true})).toBeEnabled()
 progressRun={...progressRun,status:'FAILED',failureStage:'METADATA',durationMs:68000,errorMessage:'远端服务不可用',issues:[{sourcePath:'/media/星际穿越.mkv',stage:'METADATA',reason:'TMDB 请求超时'}]}
 await expect(card.getByText('执行失败',{exact:true})).toBeVisible()
 await card.getByText('查看失败详情（1）',{exact:true}).click()
 await expect(card.getByText('刮削元数据：TMDB 请求超时',{exact:true})).toBeVisible()
 await expect(card.getByRole('progressbar')).toHaveAttribute('aria-valuenow','37')
 await page.screenshot({path:testInfo.outputPath('progress-failure.png'),fullPage:true})
 await page.unroute('**/api/task-config/*/runs/latest')
 await page.unroute('**/api/task-config/*/cancel')
 await page.setViewportSize({width:1280,height:720})
 await page.getByTitle('手动刮削',{exact:true}).click()
 await expect(page).toHaveURL(/manual-scraping/)
 await expect(page.getByText('Mayday.2026.1080p.mkv',{exact:true}).first()).toBeVisible()
 await expect(page.locator('header').getByTitle('查看 GitHub 仓库')).toHaveAttribute('href','https://github.com/Moersity/ostrm')
 const tailResponse = page.waitForResponse(r => r.url().includes('/api/logs/backend/tail'))
 await page.goto('/logs')
 expect((await tailResponse).status()).toBe(200)
 await expect(page.getByText('最后更新：暂无', {exact:true})).toHaveCount(0)
 const downloaded = page.waitForEvent('download')
 await page.getByRole('button',{name:'下载完整日志',exact:true}).click()
 expect((await downloaded).suggestedFilename()).toMatch(/backend.*\.log/)
 let latest = '99.0.0'
 await page.route('**/api/version/check', async route => {
   expect(route.request().headers().authorization).toMatch(/^Bearer /)
   await route.fulfill({json:{code:200,data:{currentVersion:'3.0.0-dev',latestVersion:latest,hasUpdate:true,canUpgrade:true,releaseUrl:'https://github.com/Moersity/ostrm/releases/tag/v'+latest}}})
 })
 await page.reload()
 await expect(page.getByText('发现新版本 99.0.0',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'跳过此版本',exact:true}).click()
 await page.reload()
 await expect(page.getByRole('button',{name:'跳过此版本',exact:true})).toHaveCount(0)
 latest = '99.1.0'
 await page.reload()
 await expect(page.getByText('发现新版本 99.1.0',{exact:true})).toBeVisible()
 await page.setViewportSize({width:390,height:844})
 await expect(page.getByRole('button',{name:'直接升级',exact:true})).toBeVisible()
 await page.route('**/api/version/upgrade', async route => {
   expect(route.request().headers().authorization).toMatch(/^Bearer /)
   if(route.request().method()==='POST') expect(route.request().postDataJSON()).toEqual({version:latest})
   await route.fulfill({json:{code:200,data:{stage:'failed',message:'升级文件 SHA-256 校验失败，已取消升级'}}})
 })
 await page.getByRole('button',{name:'直接升级',exact:true}).click()
 await expect(page.getByText('升级文件 SHA-256 校验失败，已取消升级',{exact:true})).toBeVisible()
 server.close()
 expect(errors).toEqual([])
})
